name: 'Gradle Build Project'
description: 'This action configures Java and builds a jar using gradle'
inputs:
  github_token:
    required: true
    description: 'The GitHub token'

runs:
  using: 'composite'
  steps:
    - name: Use Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: gradle

    - name: Build project
      run: ./gradlew clean assemble --no-daemon
      shell: bash
      env:
        PACKAGE_TOKEN: ${{ inputs.github_token }}
