name: 'Publish Docker Image'
description: 'This action authorises a repository, builds and pushes a docker image'
inputs:
  should_push:
    required: false
    description: 'Whether to push the image or just build'
    default: 'true'
  registry:
    required: false
    description: 'The registry to use'
    default: 'quay.io'
  username:
    required: false
    description: 'The registry username'
    default: ${{ secrets.QUAY_ROBOT_USER_NAME }}
  password:
    required: false
    description: 'The registry password'
    default: ${{ secrets.QUAY_ROBOT_TOKEN }}
  image:
    required: false
    description: 'The docker image'
    default: ${{ inputs.image }}
  tag:
    required: true
    description: 'The tag to use for the docker image'
  tag_latest:
    required: false
    description: 'Whether to tag latest'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Login to repository
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.repository }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Calculate metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image }}
        tags: |
          type=raw,value=${{ inputs.tag }}
          type=raw,value=latest,enable=${{ github.base_ref == 'main' }}

    - name: Build container
      uses: docker/build-push-action@v3
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
