name: 'Docker Build Branch - npm'
on:
  workflow_call:
    inputs:
      images:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: 16

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: 'Branch Publish'
    if: contains(github.event.pull_request.labels.*.name, 'smoketest') == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Calculate metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.images }}
          tags: |
            type=raw,value=${{ github.event.pull_request.head.sha }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm --loglevel warn ci --production=false --no-optional

      - name: Build project
        run: npm run build-prod

      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
