name: 'Docker Build Branch - Gradle'
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: 'Branch Publish'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        uses: UKHomeOffice/hocs-github-actions/.github/actions/gradle-build-project@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish branch image
        uses: UKHomeOffice/hocs-github-actions/.github/actions/docker-build-publish@v3
        with:
          should_push: ${{ !contains(github.event.pull_request.labels.*.name, 'smoketest') }}
          tag: ${{ github.event.pull_request.head.sha }}
