name: 'Lint'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    name: 'Dockerfile Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: lint
        run: docker-compose config
