name: 'Maven Publish Tag - Gradle'
on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    name: 'Main Publish'
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate SemVer value
        id: calculate
        uses: UKHomeOffice/hocs-github-actions/.github/actions/calculate-semver-value@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_to_highest: ${{ github.base_ref == 'main' }}

      - name: Build project
        uses: UKHomeOffice/hocs-github-actions/.github/actions/gradle-build-project@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish artifact
        run: ./gradlew publish -PartifactVersion=${{ steps.calculate.outputs.version }}
        env:
          PACKAGE_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Tag Repository
        uses: UKHomeOffice/semver-tag-action@v3
        with:
          tag: ${{ steps.calculate.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post failure to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1
        if: ${{ failure() }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "GitHub Action failure: ${{github.repository}}\nRun: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}\nOriginating PR: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
