name: 'SemVer label Checker'
on:
  pull_request:
    types: [ labeled, unlabeled, opened, reopened, synchronize ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: 'Check For Valid Label'
    runs-on: ubuntu-latest

    steps:
      - name: Calculate SemVer value
        uses: UKHomeOffice/hocs-github-actions/.github/actions/calculate-semver-value@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_to_highest: ${{ github.base_ref == 'main' }}
