name: 'Test - Gradle'
on:
  workflow_call:
    inputs:
      components:
        required: false
        type: string
      dependencies:
        required: false
        type: string
      elastic:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Unit and Integration Tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build project
        uses: UKHomeOffice/hocs-github-actions/.github/actions/gradle-build-project@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start integration infrastructure
        uses: UKHomeOffice/hocs-github-actions/.github/actions/start-integration-infrastructure@v3
        with:
          dependencies: ${{ inputs.dependencies }}
          components: ${{ inputs.components }}
          include_elastic: ${{ inputs.elastic }}

      - name: Run tests
        run: ./gradlew test --no-daemon
